---
info:
  title: Mettle Deps
  description: Dependencies for mettle
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/mettle-deps
  x-cortex-tag: mettle-deps
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
  x-cortex-groups:
  - exposure:external-ship
openapi: 3.0.1
servers:
- url: "/"
